export enum ErrorTypes{
    LOGIN_ERROR,
    REGISTER_HELPER_ERROR,
    UNKNOWN_ERROR,
    REGISTER_EXCHANGER_ERROR,
    FILIALES_ERROR,
    ITEMCATEGORYS_ERROR,
    EXCHANGER_ERROR,
    EDIT_ITEM_ERROR,
    EDIT_PROFILE_ERROR,
    AUTH_CODE_ERROR,
    END_DAY_ERROR,
    DONATION_ERROR,
}